# Generated by Django 5.2.4 on 2025-08-05 14:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300, verbose_name='正文')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('last_modify_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last modify time')),
                ('is_enable', models.BooleanField(default=False, verbose_name='enable')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment', verbose_name='parent comment')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comment',
                'ordering': ['-id'],
                'get_latest_by': 'id',
            },
        ),
    ]
