# Generated by Django 5.2.4 on 2025-08-05 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnTrackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=100, verbose_name='用户')),
                ('lat', models.FloatField(verbose_name='纬度')),
                ('lon', models.FloatField(verbose_name='经度')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'OwnTrackLogs',
                'verbose_name_plural': 'OwnTrackLogs',
                'ordering': ['creation_time'],
                'get_latest_by': 'creation_time',
            },
        ),
    ]
